### ISSUE TITLE
Dúvidas...

### ISSUE THREAD

**Issue by PauloBoaventura** [bubbwebstudio/bubb-correios#1]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

S.O = Centos7 - Plesk
Php = 5.6 / 7.0

**Comment by lucascolette** [comment]
Duplicado [#5](https://github.com/bubbstore/correios/issues/5)

**Comment by PauloBoaventura** [comment]
Olá @lucascolette 
Não é duplicado, mas sim... Pelo que noto são dois repositórios diferentes.... (entendimento do usuario).
Se tratam como o mesmo/duplicado eu não notei. Pois o que consta são dois projetos relacionados á CEP por dois repositórios.
Então para resumir... 
Preciso de uma implementação eficaz para magento 1.9 ou 2.1 para a impletação CEP.
Seja ela paga ou não. E minha dúvida permanece, sobre qual destas tantas aplicações "desatualizadas", ou não; poderá solucionar...

Caso tenha alguma sugestão, fico no aguardo...
